# Generated by Django 5.1.7 on 2025-04-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('author', models.CharField(blank=True, max_length=256, null=True)),
                ('tags', models.CharField(blank=True, max_length=256, null=True)),
                ('song_path', models.FileField(upload_to='assets/songs/')),
                ('hls_playlist', models.CharField(blank=True, max_length=500)),
                ('album_thumbnail', models.CharField(blank=True, max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'music',
            },
        ),
    ]
