# Generated by Django 5.1.7 on 2025-04-01 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='author',
            new_name='artist',
        ),
        migrations.RenameField(
            model_name='music',
            old_name='song_path',
            new_name='file',
        ),
    ]
